---
version: "2.4"

services:
  app:
    build: app
    ports:
      - 8080:8080
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://db:5432/sample
      DB_USER: test
      DB_PASSWORD: test

  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sample
    volumes:
      - data:/var/lib/postgresql/data
    mem_limit: 512M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs