micronaut:
  application:
    name: my-app

datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
    initialization-fail-timeout: 10000